export const SEARCH_START = "SEARCH_START";
export const SEARCH_SUCCESS = "SEARCH_SUCCESS";
export const SEARCH_FAIL = "SEARCH_FAIL";

export const SEARCH_RESULT_START = "SEARCH_RESULT_START";
export const SEARCH_RESULT_SUCCESS = "SEARCH_RESULT_SUCCESS";

export const CLEAR_SEARCH_RESULTS = "CLEAR_SEARCH_RESULTS";
